eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka

server:
  port: 8082

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8081"
            allowedHeaders: "*"
            allowedMethods: "*"
  jackson:
    defaultPropertyInclusion: NON_NULL

#secret key - should be encrypted
jwt:
  secret: secretkey



